const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Behaviors.Tween,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Behaviors.Orbit,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{jogador: 0},
	{Fixar: 0},
	{Piscar: 0},
	{animação: 0},
	{Teclado: 0},
	{Senóide: 0},
	{jóia: 0},
	{Âncora: 0},
	{pontos: 0},
	{açaão: 0},
	{inimigo1: 0},
	{marcador: 0},
	{espinhos: 0},
	{Sprite2: 0},
	{Áudio: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Sólido: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{Sprite3: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Sprite4: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Câmera3D: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{PlanoDeFundoEmBlocos9: 0},
	{Texto: 0},
	{Texto2: 0},
	{Sprite13: 0},
	{Texto3: 0},
	{Interpolação: 0},
	{derrote: 0},
	{Texto5: 0},
	{colete: 0},
	{Sprite: 0},
	{Sprite10: 0},
	{Botão: 0},
	{Mouse: 0},
	{Órbita: 0},
	{win: 0},
	{Sprite11: 0},
	{Sprite14: 0},
	{PlanoDeFundoEmBlocos10: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Texto4: 0},
	{gameOver: 0},
	{Sprite15: 0},
	{PlanoDeFundoEmBlocos11: 0},
	{Sprite12: 0},
	{Sprite16: 0}
];

self.InstanceType = {
	jogador: class extends self.ISpriteInstance {},
	animação: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	jóia: class extends self.ISpriteInstance {},
	pontos: class extends self.ITextInstance {},
	inimigo1: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	espinhos: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Câmera3D: class extends self.IInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos9: class extends self.ITiledBackgroundInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	derrote: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	colete: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Mouse: class extends self.IInstance {},
	win: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos10: class extends self.ITiledBackgroundInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	gameOver: class extends self.ITextInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos11: class extends self.ITiledBackgroundInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {}
}